---
title: "Building the subreddt_month database"
author: "Emilio Robleda"
date: "`r Sys.Date()`"
output: html_document
---
### Load libraries and data

```{r Load Libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(tibble)
library(zoo)
library(readr)

```

```{r load data}
# Unzip folder and load data
zip_folder <- "data.zip"
file_to_extract <- "data.csv"
destination_path <- "./"  # Specify the desired destination path

unzip(zip_folder, files = file_to_extract, exdir = destination_path)
data <- read_csv("data.csv")

```

### Basic descriptive stats

Structure of the raw data

```{r display structure}
str(data)

```

### Data manipulation

Change the format of date variables

```{r dates in format}
# Create a new variable called "comment_date"
data$comment_date <- as.Date(data$date, format = "%m/%d/%Y", na.rm = TRUE)
data$comment_date[is.na(data$comment_date)] <- as.Date(data$date[is.na(data$comment_date)])
# Convert "post_date" variable to date format (DD/MM/YYYY)
data$posts_date <- as.Date(data$post_date, format = "%m/%d/%Y", na.rm = TRUE)
data$posts_date[is.na(data$posts_date)] <- as.Date(data$post_date[is.na(data$posts_date)])

```

Include new variables

```{r new variables}
data <- data %>%
  mutate(
    # Dummy to see if comment was deleted
    deleted = ifelse(comment == "[deleted]", 1, 0),
    # Dummy to see if comment was deleted
    removed = ifelse(comment == "[removed]", 1, 0),
    # Dummy to see if comment was deleted or removed
    deleted_removed = ifelse(deleted == 1 | removed == 1, 1, 0),
    # Dummy to see if the AutoMod was the author of a comment
    automod = ifelse(author == "AutoModerator", 1, 0),
    # Dummy to see if the post was submit during the Euro 2022 (for this research, in July 2022)
    during_euros = ifelse(posts_date >= as.Date("2022-07-01") & posts_date < as.Date("2022-08-01"), 1, 0),
    # Dummy to see if the post was submitted after the Euro 2022 (Aug-2022 onwards)
    after_euros = ifelse(posts_date >= as.Date("2022-08-01"), 1, 0),
    # Treatment group is one of those four subreddits (their teams had a player in England's Euro 2022 squad) 
    treatment = ifelse(subreddit %in% c("reddevils", "chelseafc", "Gunners", "MCFC"), 1, 0),
    # Have a dummy of only one observation per unique post (to calculate avg_post_score later)
    first_comment = ifelse(duplicated(post_timestamp), 0, 1),
    # Calculate the length in terms of characters (NOT TOKENS) per comment
    comment_chars = ifelse(deleted == 1 | removed == 1 | automod == 1, NA, nchar(comment)),
    # Create a month 
    month_year = paste(year(posts_date), month(posts_date), sep = "-"),
    # Create a subreddit_month character variable
    subreddit_month = paste(subreddit, month_year, sep = "_"))

data <- data %>%
  # Group by unique posts
  group_by(post_timestamp) %>%
  # Create a dummy to know whether the post's thread had at least one deleted or removed comment
  mutate(moderated_post = ifelse(first_comment == 1 & any(deleted_removed == 1), 1, 0)) %>%
  # Ungroup data
  ungroup()

```

### Building a subreddit_month panel structure of the data

```{r subreddit_month panel}
subreddit_stats <- data %>%
  # Filter observations where the comment was from the AutoModerator
  filter(automod != 1) %>%
  # Group by subreddit
  group_by(subreddit_month) %>%
  summarize(
    # Group dummy; g==1 means treatment group
    g = ifelse(any(treatment == 1), 1, 0),
    # Time dummy; t==1 meant post_treatment (JULY 2022 is neither pre nor post treatment)
    t = ifelse(any(after_euros ==1), 1, 0),
    # Treatment dummy; z==1 means post_treatment observations for treatment group units
    z = ifelse(any(g == 1 & t == 1), 1, 0),
    # Total number of posts
    posts = n_distinct(post_timestamp),
    # Total number of comments
    comments = n(),
    # Mean comments per post
    avg_com = round(comments/posts,1),
    # Mean score per comment
    avg_score = round(mean(score),1),
    # Number of characters per comment 
    avg_chars = round(mean(comment_chars, na.rm = T),1),
    # Mean post_score per distinct post
    avg_post_score = round(mean(post_score[first_comment == 1]),1),
    # Counter of moderated posts (at least 1 deleted or removed comment in thread)
    moderated_posts = sum(moderated_post==1, na.rm = TRUE),
    # Proportion of posts that included moderation
    mod_prop = round(moderated_posts/posts,3),
    # Total number of deleted comments
    del_com = sum(deleted == 1, na.rm = TRUE),
    # Total number of removed comments
    rem_com = sum(removed == 1, na.rm = TRUE),
    # Proportion of deleted comments
    del_prop = round(del_com/comments,3),
    # Proportion of removed comments
    rem_prop = round(rem_com/comments,3)) %>%
  mutate(
    # Extract subreddit
    subreddit = sub("(.*)_.*", "\\1", subreddit_month),
    # Extract month
    month = sub(".*_(.*)", "\\1", subreddit_month)) %>%
  # Convert to data frame
  as.data.frame()

# Put month in "Mon-2020" format  
subreddit_stats$month <- as.yearmon(subreddit_stats$month, format = "%Y-%m")

# Select variables in desired order and arrange by subreddit and month 
subreddit_stats <- subreddit_stats %>%
  select(subreddit, month, g, t, z, posts, comments, avg_com, avg_score, avg_post_score,
         avg_chars, moderated_posts, mod_prop, del_com, rem_com, del_prop, rem_prop) %>%
  arrange(month) %>%
  arrange(subreddit)

```

### Save data as .csv file

```{r view data and save as csv}
# Show stats
write.csv(subreddit_stats, file = "subreddit_stats.csv", row.names = T)

```

```{r}
# See context of Data


```
